version: 2
jobs:
  build:
    docker:
      - image: xiaofengyear/ubuntu:19.04 

    steps:
      - checkout
      - run: 
          name: Install updates and dependencies
          command: |
              apt-get update -y
              apt-get install -y make cmake g++ git 

      - run:
          name: Pull submodules
          command: |
              GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --force --init 

      - run: 
          name: Create the build folder and entern it
          command: |
              mkdir build
              cd build

      - run:
          name: Compile the codes
          command: |
              cmake ..
              make

      - run:
          name: Run the test
          command: GTEST_COLOR=1 CTEST_OUTPUT_ON_FAILURE=1 make test
