version: 2
jobs:
  build:
    docker:
      - image: xiaofengyear/ubuntu:19.04 

    steps:
      - checkout
      - run: 
          name: Install updates and git
          command: |
              apt-get update -y
              apt-get install -y git 

      - run:
          name: Pull submodules
          command: |
              GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --force --init 

      - run: 
          name: Create the build folder
          command: mkdir build

      - run:
          name: Compile the codes
          command: |
              cd build
              cmake ..
              make

      - run:
          name: Run the test
          command: |
              cd build
              GTEST_COLOR=1 CTEST_OUTPUT_ON_FAILURE=1 make test

